language: go

sudo: required
dist: trusty

services:
  - docker

go:
  - 1.11.x
  - master
  - tip

env:
  matrix:
    - LIBVIPS=8.5.9
    - LIBVIPS=8.6.3
    - LIBVIPS=8.7.0
  global:
    - GO111MODULE=on
    - secure: "J1RMy1EvaaETsSxKXe2T1j9KcQDAgMb3On0+3Nd+Puq2ZVbBuGgYmh8eR4bYpG5RPN9MZPf4/zfaTugAD3cT0Ks1H1aFy/1LS4/Vrh+ppxWh7Xuj/A0Y5HAzC5dFMI7s9DU4OeRp/6bE229Cg3nJFIqGuOgsr066PQ2QeXYYtNOiYWgj2BE20KGlQgHeowocTKjPYgmxbAdHHU7bqrr1mcmMPMWnjzVHyphbWj2WnafAZ0AhSk9LCABVfUCUmMXnMddHfn/J/vCMbh1Cm105eKnRKFqrlqyfg/Owb17vN/EbB4KoqNW/OIEqZMO+Frf5U1AePudLZUqy1ZuChFS0g7GdMgNDw6IkZ0nPJ76PlGyUIJrl8hpAFhHqccan0PRVnzki1DCspDL9GBU13SZmZQUwNkFf1vWehXywUJaJ6mBVgrXdeNOvpU0W9sI+QC6tOZq42FT4yTS1jYeLOYhbgcmk6TY8JJGCN3/3G/kMB2e2CONudAryo09yZdWIquFaAWK0eN4ld1k5oYcTAWsYN8Gz2Ett/twvTgdrMnEUZlwO0h9HE629FG/0r+U7vLXnnT+reeSLfJsVDaYbO/jKuMD57zMOWNbiSM2orqqFlnclShSAyRHaXuCbf55SkLqxIWdlKlDgvMwVUqNJ4VnVt6AwOgBUvLouBI11ZNOWv0k=" # DOCKER_USER
    - secure: "Uzl9KwJUpAImAuA6ig4q3/6IotZd9LXSJxucbvZ/nZN3mGknFffLJDlDQ/+wPgqDbnNwrHKhp7HhIw2SPeyHcR+8w4HQJvdA3T1UKfERYnrxwjHti6dmM/HM0h7CqTP8GncCh3HtD6mSeluOVF4gULF06u+andEae+a7AupIuZELtxz/+aFi4uRxa3rf2Ya0FPU9NoJoI29cwclhX/ywWUtV0eMuoX4P6qGS/8M60HPLqPvMUsXfLdiwJztp2vpIJFvNg5AzZrYNjAKWyHGX6KAf4OhtMrsqkFen5iFvVuFcfJBP1COJ+kw/mxH4wESF1j4vPAXJDTyObjpuTPuLzMNTiMVet9bCJEmZkyjogIxIPMcT8o+iorgpUk+NsXpavc+IjfhTOnS11xvALWbRXZrlkXNWO6gcK0y49WvZuwQ1t46nOas5QQ3ToP6aQtarxNYUIsHZkUWQuBMifrMOURR3Gbyid9UYFDIMuDNBov5tDYClPHMVFu2s9GkOzu6Xqm4bGT8MJdQDKMQ7NA1hocyR20v7oWiZJ7niL26BngX244kGEIV53wbPvqJ94rh6Gm9YS11/QxSqUR6wk5Z6trVLqSjmWBaPYt008FmfLxSlwjxN4HAYO2fAZXr+uLifaT5La+3F8kQDYw6Pf4SnL5N6GbLlvrLmsBTeBBJVugY=" # DOCKER_PASS

matrix:
  fast_finish: true
  allow_failures:
    - go: master
    - go: tip

cache:
  apt:
  directories:
    - $HOME/libvips

addons:
  apt:
    packages:
      - gobject-introspection
      - gtk-doc-tools
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - libwebp-dev

before_install:
  - wget https://github.com/jcupitt/libvips/archive/v$LIBVIPS.zip
  - unzip v$LIBVIPS
  - cd libvips-$LIBVIPS
  - test -f autogen.sh && ./autogen.sh || ./bootstrap.sh
  - >
    CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0
    ./configure
    --disable-debug
    --disable-dependency-tracking
    --disable-introspection
    --disable-static
    --enable-gtk-doc-html=no
    --enable-gtk-doc=no
    --enable-pyvips8=no
    --without-orc
    --without-python
    --prefix=$HOME/libvips
    $1
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - export PATH=$PATH:$HOME/libvips/bin
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/libvips/lib/pkgconfig
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/libvips/lib
  - vips --vips-version

install:
  - go get github.com/mattn/goveralls

script:
  - make coverage

after_success:
  - goveralls -coverprofile=./build/coverage.out -service=travis-ci

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      tags: false
      branch: develop
