language: go

sudo: required
dist: trusty

go:
  - 1.11.x
  - master
  - tip

env:
  matrix:
    - LIBVIPS=8.5.9
    - LIBVIPS=8.6.3
    - GO111MODULE=on
  global:
    - DOCKER_REGISTRY=registry.heroku.com
    - secure: MY1vayWZpblN1TtbH3bhbNobc+JyoXYdGM2AorVeNu3mUEa4tuHXQHT/hYXS4cdW2ckZJtF964zE1MN4xyg+dr7uu7knZzF5RK4Mr41hWZBHPfE+Lt7dTH7U2Wzor4Rn4bnPUS/obVXHRtNG6G/FKsz/S1De3YV7cda0KbehXsti5NJ8jj/FcXIDV/DvbDTceZcVFhQ2WCQqU110yRyLLMQJgZPEoOmLHFvVvzfV/wtfQ7kCL2HJ5QOLrT79dj579NL4AYFPIR0GCJ8V9cMSOwzy5acp/KUYxfGKGjQfgDVyQMMmVe6NOxJjcdlmdlQPfEUDW3dRviIV5Z8n8dZLTFMNS5bo3rzTOkuf7878B8ZI7ZyPaLUL9EGOSN1LWYyCkshwPwIzSqY6AEmu7DRCMoB2fwMblDbPHO9KnVWjgL9MRMnY7+FwgIIiLOxK1prNmiKeXCB7nqc44MfXgtpd1xxAxMGlfWBIbHaxrXsflCwYdqrpuD1dW2n5IVGIx6BxRaQJIB318PcqnflFkSVNPFYSArKP+PoZp7hWTu4u4EBAKCRGL0j244O1fHt4+2vgzYHGwakQPN9OXwTU5pojYP4g4MElnKp9s16hGMcjft2BWljBuVWssa46WV22vcaPJp8wjl4v/GcWdHrHI0vB/LR4q0QEjUiBrdbD+KUnV18= # DOCKER_USER
    - secure: Fd5cCYLvIcjc0eNMOrkXsR5ySzGQaAox9QBIF62Z1vo2sx9LzxW2O+oaPB+rEJmfE+l1MXACl3yioGir9EZuFLgNbKz1lJ0pJcnTu/rVt46AmMKx+ZgmRA/xDMYabehlYb9rrWt1vitLPFCZPKOiSvqbGoLFAbq+A40s86MLJkdhV4Z7VuMy8EiWBLGTe35WbmgwXLhgW+TTcgF8VGbV7ns1v2iEj5k94BM/g3Yy65bkhKzTWAugPqKZ2zVobtA1CwO4FTCi4LF7B5jXQPuhrxD04w616GFBxS1KNSPywza5SBfIYRzrwcHbe216JaWeapDGkNLOSWKbNaV5dnAdzdUHTsyWUqs7L5AQjYPtJk7GF7MCroK4N7Xcu4HMW1FV6O2lODM0jfpb22xP0SW4Q+EtgQWWLFW3EiOmaT1TIbMDJVbWOeiu7yfLbdntKS7N54/QwMIzADfYPJ4jVh8diMLYXxYcdUPB44pdszuu7TucKHYkNVtcfjK9gUBUP+ooGdjFt2fkYX4EHbfo56EWDzCfJxMJjJEI3A8TQ27+Ma0zZlXbyOAeg/1iSKE1e9Zi+rKao+87u4xXc4TPb+RdGlVs6Er/jiVhDo/eEBUkHOGnzBUdAV/y9sGrdBu7fQkbEHTAWtoCs1c2sOqc60Bkb6m9eHo6gO0IvLOEWU34Myg= # DOCKER_PASS

matrix:
  fast_finish: true
  allow_failures:
    - go: master
    - go: tip

cache:
  apt:
  directories:
    - $HOME/libvips

addons:
  apt:
    packages:
      - gobject-introspection
      - gtk-doc-tools
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - libwebp-dev

before_install:
  - wget https://github.com/jcupitt/libvips/archive/v$LIBVIPS.zip
  - unzip v$LIBVIPS
  - cd libvips-$LIBVIPS
  - test -f autogen.sh && ./autogen.sh || ./bootstrap.sh
  - >
    CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0
    ./configure
    --disable-debug
    --disable-dependency-tracking
    --disable-introspection
    --disable-static
    --enable-gtk-doc-html=no
    --enable-gtk-doc=no
    --enable-pyvips8=no
    --without-orc
    --without-python
    --prefix=$HOME/libvips
    $1
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - export PATH=$PATH:$HOME/libvips/bin
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/libvips/lib/pkgconfig
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/libvips/lib
  - vips --vips-version

install:
  - go get github.com/mattn/goveralls

script:
  - make coverage

after_success:
  - goveralls -coverprofile=./build/coverage.out -service=travis-ci
#  - docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REGISTRY

#deploy:
#  - provider: script
#    script: scripts/deploy.sh $TRAVIS_TAG
#    on:
#      tags: true
#      branch: master

#deploy:
#  on:
#    condition: $TRAVIS_GO_VERSION =~ ^1\.8\.[0-9]+$
